////
  // Copyright (c) 2018-2023 TNO and Contributors to the GitHub community
  //
  // This program and the accompanying materials are made available
  // under the terms of the MIT License which is available at
  // https://opensource.org/licenses/MIT
  //
  // SPDX-License-Identifier: MIT
////

include::_initCommon.adoc[]

// Enable custom style in _main-docinfo.html
:docinfo:

= PPS User Guide

ifdef::output-site[]
ifdef::output-html[]
TIP: The user guide is also available in the Eclipse Help (via menu menu:Help[Help Contents] and it can be link:pps-user-guide.pdf[downloaded as a PDF].
endif::output-html[]
endif::output-site[]

This user guide describes how to use the Platform Performance Suite (PPS).
PPS provides insight in software execution over time and enables automatic performance diagnostics.
Various generic analysis techniques like critical path, root-cause, outlier identification analysis can be applied to the Timed Message Sequence Chart (TMSC) model.
The TMSC-models, as well as the results of the analysis, are presented to the user by various visualizations focusing on facilitating the diagnosis at specific abstraction levels.

<<<

include::_section_workbench.adoc[]

<<<

include::_section_tmsct_editor.adoc[]

<<<

include::_section_tmsc_editor.adoc[]
<<<

include::_section_common_viewer.adoc[]
<<<

include::_section_release-notes.adoc[]
