/**
 * Generated by Xtext, all rights reserved ESI (TNO)
 */
package nl.esi.pps.tmsc.xtext.tmscXtext.impl;

import nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextFactory;
import nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextModel;
import nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage;
import nl.esi.pps.tmsc.xtext.tmscXtext.XArchitectureKind;
import nl.esi.pps.tmsc.xtext.tmscXtext.XComponent;
import nl.esi.pps.tmsc.xtext.tmscXtext.XDependency;
import nl.esi.pps.tmsc.xtext.tmscXtext.XDependencySettings;
import nl.esi.pps.tmsc.xtext.tmscXtext.XDependencyType;
import nl.esi.pps.tmsc.xtext.tmscXtext.XDependencyTypeObject;
import nl.esi.pps.tmsc.xtext.tmscXtext.XEvent;
import nl.esi.pps.tmsc.xtext.tmscXtext.XEventArgument;
import nl.esi.pps.tmsc.xtext.tmscXtext.XEventType;
import nl.esi.pps.tmsc.xtext.tmscXtext.XExecutor;
import nl.esi.pps.tmsc.xtext.tmscXtext.XFunction;
import nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameter;
import nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameterKind;
import nl.esi.pps.tmsc.xtext.tmscXtext.XHost;
import nl.esi.pps.tmsc.xtext.tmscXtext.XInterface;
import nl.esi.pps.tmsc.xtext.tmscXtext.XNamedArchitectureElement;
import nl.esi.pps.tmsc.xtext.tmscXtext.XOperation;
import nl.esi.pps.tmsc.xtext.tmscXtext.XProperty;
import nl.esi.pps.tmsc.xtext.tmscXtext.XPropertyBooleanValue;
import nl.esi.pps.tmsc.xtext.tmscXtext.XPropertyMutliValue;
import nl.esi.pps.tmsc.xtext.tmscXtext.XPropertyNumberValue;
import nl.esi.pps.tmsc.xtext.tmscXtext.XPropertyStringValue;
import nl.esi.pps.tmsc.xtext.tmscXtext.XPropertyValue;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TmscXtextPackageImpl extends EPackageImpl implements TmscXtextPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tmscXtextModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xNamedArchitectureElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xInterfaceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xComponentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xFunctionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xFunctionParameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xHostEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xExecutorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xEventEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xEventArgumentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xDependencyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xDependencyTypeObjectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xDependencySettingsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xPropertyValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xPropertyStringValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xPropertyNumberValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xPropertyBooleanValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xPropertyMutliValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum xArchitectureKindEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum xFunctionParameterKindEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum xEventTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum xDependencyTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private TmscXtextPackageImpl()
  {
    super(eNS_URI, TmscXtextFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link TmscXtextPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static TmscXtextPackage init()
  {
    if (isInited) return (TmscXtextPackage)EPackage.Registry.INSTANCE.getEPackage(TmscXtextPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredTmscXtextPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    TmscXtextPackageImpl theTmscXtextPackage = registeredTmscXtextPackage instanceof TmscXtextPackageImpl ? (TmscXtextPackageImpl)registeredTmscXtextPackage : new TmscXtextPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theTmscXtextPackage.createPackageContents();

    // Initialize created meta-data
    theTmscXtextPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theTmscXtextPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(TmscXtextPackage.eNS_URI, theTmscXtextPackage);
    return theTmscXtextPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTmscXtextModel()
  {
    return tmscXtextModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTmscXtextModel_ArchitectureKind()
  {
    return (EAttribute)tmscXtextModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTmscXtextModel_TimeBound()
  {
    return (EAttribute)tmscXtextModelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTmscXtextModel_Scheduled()
  {
    return (EAttribute)tmscXtextModelEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTmscXtextModel_Properties()
  {
    return (EReference)tmscXtextModelEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTmscXtextModel_DependencySettings()
  {
    return (EReference)tmscXtextModelEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTmscXtextModel_Interfaces()
  {
    return (EReference)tmscXtextModelEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTmscXtextModel_Components()
  {
    return (EReference)tmscXtextModelEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTmscXtextModel_Functions()
  {
    return (EReference)tmscXtextModelEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTmscXtextModel_Hosts()
  {
    return (EReference)tmscXtextModelEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTmscXtextModel_Executors()
  {
    return (EReference)tmscXtextModelEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTmscXtextModel_Events()
  {
    return (EReference)tmscXtextModelEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXNamedArchitectureElement()
  {
    return xNamedArchitectureElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXNamedArchitectureElement_Description()
  {
    return (EAttribute)xNamedArchitectureElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXNamedArchitectureElement_Name()
  {
    return (EAttribute)xNamedArchitectureElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXNamedArchitectureElement_Properties()
  {
    return (EReference)xNamedArchitectureElementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXInterface()
  {
    return xInterfaceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXInterface_Operations()
  {
    return (EReference)xInterfaceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXOperation()
  {
    return xOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXComponent()
  {
    return xComponentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXComponent_Provides()
  {
    return (EReference)xComponentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXComponent_Requires()
  {
    return (EReference)xComponentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXComponent_TimeBound()
  {
    return (EAttribute)xComponentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXComponent_Scheduled()
  {
    return (EAttribute)xComponentEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXFunction()
  {
    return xFunctionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXFunction_IpcClient()
  {
    return (EAttribute)xFunctionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXFunction_IpcServer()
  {
    return (EAttribute)xFunctionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXFunction_Parameters()
  {
    return (EReference)xFunctionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXFunction_Operation()
  {
    return (EReference)xFunctionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXFunction_TimeBound()
  {
    return (EAttribute)xFunctionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXFunction_Scheduled()
  {
    return (EAttribute)xFunctionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXFunctionParameter()
  {
    return xFunctionParameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXFunctionParameter_Kind()
  {
    return (EAttribute)xFunctionParameterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXFunctionParameter_Name()
  {
    return (EAttribute)xFunctionParameterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXFunctionParameter_Properties()
  {
    return (EReference)xFunctionParameterEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXHost()
  {
    return xHostEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXHost_Untraced()
  {
    return (EAttribute)xHostEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXHost_TimeBound()
  {
    return (EAttribute)xHostEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXHost_Scheduled()
  {
    return (EAttribute)xHostEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXHost_Executors()
  {
    return (EReference)xHostEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXExecutor()
  {
    return xExecutorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXExecutor_Untraced()
  {
    return (EAttribute)xExecutorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXExecutor_TimeBound()
  {
    return (EAttribute)xExecutorEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXExecutor_Scheduled()
  {
    return (EAttribute)xExecutorEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXEvent()
  {
    return xEventEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXEvent_Timestamp()
  {
    return (EAttribute)xEventEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXEvent_TimeBound()
  {
    return (EAttribute)xEventEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXEvent_Executor()
  {
    return (EReference)xEventEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXEvent_Component()
  {
    return (EReference)xEventEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXEvent_Type()
  {
    return (EAttribute)xEventEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXEvent_Function()
  {
    return (EReference)xEventEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXEvent_Arguments()
  {
    return (EReference)xEventEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXEvent_OutgoingDependencies()
  {
    return (EReference)xEventEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXEvent_IncomingDependencies()
  {
    return (EReference)xEventEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXEvent_Scheduled()
  {
    return (EAttribute)xEventEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXEvent_Properties()
  {
    return (EReference)xEventEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXEventArgument()
  {
    return xEventArgumentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXEventArgument_Parameter()
  {
    return (EReference)xEventArgumentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXEventArgument_Value()
  {
    return (EAttribute)xEventArgumentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXDependency()
  {
    return xDependencyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXDependency_TypeObject()
  {
    return (EReference)xDependencyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXDependency_Name()
  {
    return (EAttribute)xDependencyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXDependency_TimeBound()
  {
    return (EAttribute)xDependencyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXDependency_Scheduled()
  {
    return (EAttribute)xDependencyEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXDependency_Request()
  {
    return (EReference)xDependencyEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXDependency_Message()
  {
    return (EReference)xDependencyEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXDependency_Properties()
  {
    return (EReference)xDependencyEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXDependencyTypeObject()
  {
    return xDependencyTypeObjectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXDependencyTypeObject_Value()
  {
    return (EAttribute)xDependencyTypeObjectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXDependencySettings()
  {
    return xDependencySettingsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXDependencySettings_Type()
  {
    return (EAttribute)xDependencySettingsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXDependencySettings_TimeBound()
  {
    return (EAttribute)xDependencySettingsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXDependencySettings_Scheduled()
  {
    return (EAttribute)xDependencySettingsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXDependencySettings_Prefix()
  {
    return (EAttribute)xDependencySettingsEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXDependencySettings_Properties()
  {
    return (EReference)xDependencySettingsEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXProperty()
  {
    return xPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXProperty_Name()
  {
    return (EAttribute)xPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXProperty_Value()
  {
    return (EReference)xPropertyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXPropertyValue()
  {
    return xPropertyValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXPropertyStringValue()
  {
    return xPropertyStringValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXPropertyStringValue_Value()
  {
    return (EAttribute)xPropertyStringValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXPropertyNumberValue()
  {
    return xPropertyNumberValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXPropertyNumberValue_Value()
  {
    return (EAttribute)xPropertyNumberValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXPropertyBooleanValue()
  {
    return xPropertyBooleanValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getXPropertyBooleanValue_Value()
  {
    return (EAttribute)xPropertyBooleanValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXPropertyMutliValue()
  {
    return xPropertyMutliValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXPropertyMutliValue_Values()
  {
    return (EReference)xPropertyMutliValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getXArchitectureKind()
  {
    return xArchitectureKindEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getXFunctionParameterKind()
  {
    return xFunctionParameterKindEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getXEventType()
  {
    return xEventTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getXDependencyType()
  {
    return xDependencyTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TmscXtextFactory getTmscXtextFactory()
  {
    return (TmscXtextFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    tmscXtextModelEClass = createEClass(TMSC_XTEXT_MODEL);
    createEAttribute(tmscXtextModelEClass, TMSC_XTEXT_MODEL__ARCHITECTURE_KIND);
    createEAttribute(tmscXtextModelEClass, TMSC_XTEXT_MODEL__TIME_BOUND);
    createEAttribute(tmscXtextModelEClass, TMSC_XTEXT_MODEL__SCHEDULED);
    createEReference(tmscXtextModelEClass, TMSC_XTEXT_MODEL__PROPERTIES);
    createEReference(tmscXtextModelEClass, TMSC_XTEXT_MODEL__DEPENDENCY_SETTINGS);
    createEReference(tmscXtextModelEClass, TMSC_XTEXT_MODEL__INTERFACES);
    createEReference(tmscXtextModelEClass, TMSC_XTEXT_MODEL__COMPONENTS);
    createEReference(tmscXtextModelEClass, TMSC_XTEXT_MODEL__FUNCTIONS);
    createEReference(tmscXtextModelEClass, TMSC_XTEXT_MODEL__HOSTS);
    createEReference(tmscXtextModelEClass, TMSC_XTEXT_MODEL__EXECUTORS);
    createEReference(tmscXtextModelEClass, TMSC_XTEXT_MODEL__EVENTS);

    xNamedArchitectureElementEClass = createEClass(XNAMED_ARCHITECTURE_ELEMENT);
    createEAttribute(xNamedArchitectureElementEClass, XNAMED_ARCHITECTURE_ELEMENT__DESCRIPTION);
    createEAttribute(xNamedArchitectureElementEClass, XNAMED_ARCHITECTURE_ELEMENT__NAME);
    createEReference(xNamedArchitectureElementEClass, XNAMED_ARCHITECTURE_ELEMENT__PROPERTIES);

    xInterfaceEClass = createEClass(XINTERFACE);
    createEReference(xInterfaceEClass, XINTERFACE__OPERATIONS);

    xOperationEClass = createEClass(XOPERATION);

    xComponentEClass = createEClass(XCOMPONENT);
    createEReference(xComponentEClass, XCOMPONENT__PROVIDES);
    createEReference(xComponentEClass, XCOMPONENT__REQUIRES);
    createEAttribute(xComponentEClass, XCOMPONENT__TIME_BOUND);
    createEAttribute(xComponentEClass, XCOMPONENT__SCHEDULED);

    xFunctionEClass = createEClass(XFUNCTION);
    createEAttribute(xFunctionEClass, XFUNCTION__IPC_CLIENT);
    createEAttribute(xFunctionEClass, XFUNCTION__IPC_SERVER);
    createEReference(xFunctionEClass, XFUNCTION__PARAMETERS);
    createEReference(xFunctionEClass, XFUNCTION__OPERATION);
    createEAttribute(xFunctionEClass, XFUNCTION__TIME_BOUND);
    createEAttribute(xFunctionEClass, XFUNCTION__SCHEDULED);

    xFunctionParameterEClass = createEClass(XFUNCTION_PARAMETER);
    createEAttribute(xFunctionParameterEClass, XFUNCTION_PARAMETER__KIND);
    createEAttribute(xFunctionParameterEClass, XFUNCTION_PARAMETER__NAME);
    createEReference(xFunctionParameterEClass, XFUNCTION_PARAMETER__PROPERTIES);

    xHostEClass = createEClass(XHOST);
    createEAttribute(xHostEClass, XHOST__UNTRACED);
    createEAttribute(xHostEClass, XHOST__TIME_BOUND);
    createEAttribute(xHostEClass, XHOST__SCHEDULED);
    createEReference(xHostEClass, XHOST__EXECUTORS);

    xExecutorEClass = createEClass(XEXECUTOR);
    createEAttribute(xExecutorEClass, XEXECUTOR__UNTRACED);
    createEAttribute(xExecutorEClass, XEXECUTOR__TIME_BOUND);
    createEAttribute(xExecutorEClass, XEXECUTOR__SCHEDULED);

    xEventEClass = createEClass(XEVENT);
    createEAttribute(xEventEClass, XEVENT__TIMESTAMP);
    createEAttribute(xEventEClass, XEVENT__TIME_BOUND);
    createEReference(xEventEClass, XEVENT__EXECUTOR);
    createEReference(xEventEClass, XEVENT__COMPONENT);
    createEAttribute(xEventEClass, XEVENT__TYPE);
    createEReference(xEventEClass, XEVENT__FUNCTION);
    createEReference(xEventEClass, XEVENT__ARGUMENTS);
    createEReference(xEventEClass, XEVENT__OUTGOING_DEPENDENCIES);
    createEReference(xEventEClass, XEVENT__INCOMING_DEPENDENCIES);
    createEAttribute(xEventEClass, XEVENT__SCHEDULED);
    createEReference(xEventEClass, XEVENT__PROPERTIES);

    xEventArgumentEClass = createEClass(XEVENT_ARGUMENT);
    createEReference(xEventArgumentEClass, XEVENT_ARGUMENT__PARAMETER);
    createEAttribute(xEventArgumentEClass, XEVENT_ARGUMENT__VALUE);

    xDependencyEClass = createEClass(XDEPENDENCY);
    createEReference(xDependencyEClass, XDEPENDENCY__TYPE_OBJECT);
    createEAttribute(xDependencyEClass, XDEPENDENCY__NAME);
    createEAttribute(xDependencyEClass, XDEPENDENCY__TIME_BOUND);
    createEAttribute(xDependencyEClass, XDEPENDENCY__SCHEDULED);
    createEReference(xDependencyEClass, XDEPENDENCY__REQUEST);
    createEReference(xDependencyEClass, XDEPENDENCY__MESSAGE);
    createEReference(xDependencyEClass, XDEPENDENCY__PROPERTIES);

    xDependencyTypeObjectEClass = createEClass(XDEPENDENCY_TYPE_OBJECT);
    createEAttribute(xDependencyTypeObjectEClass, XDEPENDENCY_TYPE_OBJECT__VALUE);

    xDependencySettingsEClass = createEClass(XDEPENDENCY_SETTINGS);
    createEAttribute(xDependencySettingsEClass, XDEPENDENCY_SETTINGS__TYPE);
    createEAttribute(xDependencySettingsEClass, XDEPENDENCY_SETTINGS__TIME_BOUND);
    createEAttribute(xDependencySettingsEClass, XDEPENDENCY_SETTINGS__SCHEDULED);
    createEAttribute(xDependencySettingsEClass, XDEPENDENCY_SETTINGS__PREFIX);
    createEReference(xDependencySettingsEClass, XDEPENDENCY_SETTINGS__PROPERTIES);

    xPropertyEClass = createEClass(XPROPERTY);
    createEAttribute(xPropertyEClass, XPROPERTY__NAME);
    createEReference(xPropertyEClass, XPROPERTY__VALUE);

    xPropertyValueEClass = createEClass(XPROPERTY_VALUE);

    xPropertyStringValueEClass = createEClass(XPROPERTY_STRING_VALUE);
    createEAttribute(xPropertyStringValueEClass, XPROPERTY_STRING_VALUE__VALUE);

    xPropertyNumberValueEClass = createEClass(XPROPERTY_NUMBER_VALUE);
    createEAttribute(xPropertyNumberValueEClass, XPROPERTY_NUMBER_VALUE__VALUE);

    xPropertyBooleanValueEClass = createEClass(XPROPERTY_BOOLEAN_VALUE);
    createEAttribute(xPropertyBooleanValueEClass, XPROPERTY_BOOLEAN_VALUE__VALUE);

    xPropertyMutliValueEClass = createEClass(XPROPERTY_MUTLI_VALUE);
    createEReference(xPropertyMutliValueEClass, XPROPERTY_MUTLI_VALUE__VALUES);

    // Create enums
    xArchitectureKindEEnum = createEEnum(XARCHITECTURE_KIND);
    xFunctionParameterKindEEnum = createEEnum(XFUNCTION_PARAMETER_KIND);
    xEventTypeEEnum = createEEnum(XEVENT_TYPE);
    xDependencyTypeEEnum = createEEnum(XDEPENDENCY_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    xInterfaceEClass.getESuperTypes().add(this.getXNamedArchitectureElement());
    xOperationEClass.getESuperTypes().add(this.getXNamedArchitectureElement());
    xComponentEClass.getESuperTypes().add(this.getXNamedArchitectureElement());
    xFunctionEClass.getESuperTypes().add(this.getXNamedArchitectureElement());
    xHostEClass.getESuperTypes().add(this.getXNamedArchitectureElement());
    xExecutorEClass.getESuperTypes().add(this.getXNamedArchitectureElement());
    xPropertyStringValueEClass.getESuperTypes().add(this.getXPropertyValue());
    xPropertyNumberValueEClass.getESuperTypes().add(this.getXPropertyValue());
    xPropertyBooleanValueEClass.getESuperTypes().add(this.getXPropertyValue());
    xPropertyMutliValueEClass.getESuperTypes().add(this.getXPropertyValue());

    // Initialize classes and features; add operations and parameters
    initEClass(tmscXtextModelEClass, TmscXtextModel.class, "TmscXtextModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTmscXtextModel_ArchitectureKind(), this.getXArchitectureKind(), "architectureKind", null, 0, 1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTmscXtextModel_TimeBound(), ecorePackage.getEBigDecimal(), "timeBound", null, 0, 1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTmscXtextModel_Scheduled(), ecorePackage.getEBooleanObject(), "scheduled", null, 0, 1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTmscXtextModel_Properties(), this.getXProperty(), null, "properties", null, 0, -1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTmscXtextModel_DependencySettings(), this.getXDependencySettings(), null, "dependencySettings", null, 0, -1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTmscXtextModel_Interfaces(), this.getXInterface(), null, "interfaces", null, 0, -1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTmscXtextModel_Components(), this.getXComponent(), null, "components", null, 0, -1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTmscXtextModel_Functions(), this.getXFunction(), null, "functions", null, 0, -1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTmscXtextModel_Hosts(), this.getXHost(), null, "hosts", null, 0, -1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTmscXtextModel_Executors(), this.getXExecutor(), null, "executors", null, 0, -1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTmscXtextModel_Events(), this.getXEvent(), null, "events", null, 0, -1, TmscXtextModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xNamedArchitectureElementEClass, XNamedArchitectureElement.class, "XNamedArchitectureElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXNamedArchitectureElement_Description(), ecorePackage.getEString(), "description", null, 0, 1, XNamedArchitectureElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXNamedArchitectureElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, XNamedArchitectureElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXNamedArchitectureElement_Properties(), this.getXProperty(), null, "properties", null, 0, -1, XNamedArchitectureElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xInterfaceEClass, XInterface.class, "XInterface", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getXInterface_Operations(), this.getXOperation(), null, "operations", null, 0, -1, XInterface.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xOperationEClass, XOperation.class, "XOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(xComponentEClass, XComponent.class, "XComponent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getXComponent_Provides(), this.getXInterface(), null, "provides", null, 0, -1, XComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXComponent_Requires(), this.getXInterface(), null, "requires", null, 0, -1, XComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXComponent_TimeBound(), ecorePackage.getEBigDecimal(), "timeBound", null, 0, 1, XComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXComponent_Scheduled(), ecorePackage.getEBooleanObject(), "scheduled", null, 0, 1, XComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xFunctionEClass, XFunction.class, "XFunction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXFunction_IpcClient(), ecorePackage.getEBoolean(), "ipcClient", null, 0, 1, XFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXFunction_IpcServer(), ecorePackage.getEBoolean(), "ipcServer", null, 0, 1, XFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXFunction_Parameters(), this.getXFunctionParameter(), null, "parameters", null, 0, -1, XFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXFunction_Operation(), this.getXOperation(), null, "operation", null, 0, 1, XFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXFunction_TimeBound(), ecorePackage.getEBigDecimal(), "timeBound", null, 0, 1, XFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXFunction_Scheduled(), ecorePackage.getEBooleanObject(), "scheduled", null, 0, 1, XFunction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xFunctionParameterEClass, XFunctionParameter.class, "XFunctionParameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXFunctionParameter_Kind(), this.getXFunctionParameterKind(), "kind", null, 0, 1, XFunctionParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXFunctionParameter_Name(), ecorePackage.getEString(), "name", null, 0, 1, XFunctionParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXFunctionParameter_Properties(), this.getXProperty(), null, "properties", null, 0, -1, XFunctionParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xHostEClass, XHost.class, "XHost", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXHost_Untraced(), ecorePackage.getEBoolean(), "untraced", null, 0, 1, XHost.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXHost_TimeBound(), ecorePackage.getEBigDecimal(), "timeBound", null, 0, 1, XHost.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXHost_Scheduled(), ecorePackage.getEBooleanObject(), "scheduled", null, 0, 1, XHost.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXHost_Executors(), this.getXExecutor(), null, "executors", null, 0, -1, XHost.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xExecutorEClass, XExecutor.class, "XExecutor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXExecutor_Untraced(), ecorePackage.getEBoolean(), "untraced", null, 0, 1, XExecutor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXExecutor_TimeBound(), ecorePackage.getEBigDecimal(), "timeBound", null, 0, 1, XExecutor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXExecutor_Scheduled(), ecorePackage.getEBooleanObject(), "scheduled", null, 0, 1, XExecutor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xEventEClass, XEvent.class, "XEvent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXEvent_Timestamp(), ecorePackage.getEBigDecimal(), "timestamp", null, 0, 1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXEvent_TimeBound(), ecorePackage.getEBigDecimal(), "timeBound", null, 0, 1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXEvent_Executor(), this.getXExecutor(), null, "executor", null, 0, 1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXEvent_Component(), this.getXComponent(), null, "component", null, 0, 1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXEvent_Type(), this.getXEventType(), "type", null, 0, 1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXEvent_Function(), this.getXFunction(), null, "function", null, 0, 1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXEvent_Arguments(), this.getXEventArgument(), null, "arguments", null, 0, -1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXEvent_OutgoingDependencies(), this.getXDependency(), null, "outgoingDependencies", null, 0, -1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXEvent_IncomingDependencies(), this.getXDependency(), null, "incomingDependencies", null, 0, -1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXEvent_Scheduled(), ecorePackage.getEBooleanObject(), "scheduled", null, 0, 1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXEvent_Properties(), this.getXProperty(), null, "properties", null, 0, -1, XEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xEventArgumentEClass, XEventArgument.class, "XEventArgument", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getXEventArgument_Parameter(), this.getXFunctionParameter(), null, "parameter", null, 0, 1, XEventArgument.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXEventArgument_Value(), ecorePackage.getEString(), "value", null, 0, 1, XEventArgument.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xDependencyEClass, XDependency.class, "XDependency", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getXDependency_TypeObject(), this.getXDependencyTypeObject(), null, "typeObject", null, 0, 1, XDependency.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXDependency_Name(), ecorePackage.getEString(), "name", null, 0, 1, XDependency.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXDependency_TimeBound(), ecorePackage.getEBigDecimal(), "timeBound", null, 0, 1, XDependency.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXDependency_Scheduled(), ecorePackage.getEBooleanObject(), "scheduled", null, 0, 1, XDependency.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXDependency_Request(), this.getXDependency(), null, "request", null, 0, 1, XDependency.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXDependency_Message(), this.getXDependency(), null, "message", null, 0, 1, XDependency.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXDependency_Properties(), this.getXProperty(), null, "properties", null, 0, -1, XDependency.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xDependencyTypeObjectEClass, XDependencyTypeObject.class, "XDependencyTypeObject", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXDependencyTypeObject_Value(), this.getXDependencyType(), "value", null, 0, 1, XDependencyTypeObject.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xDependencySettingsEClass, XDependencySettings.class, "XDependencySettings", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXDependencySettings_Type(), this.getXDependencyType(), "type", null, 0, 1, XDependencySettings.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXDependencySettings_TimeBound(), ecorePackage.getEBigDecimal(), "timeBound", null, 0, 1, XDependencySettings.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXDependencySettings_Scheduled(), ecorePackage.getEBooleanObject(), "scheduled", null, 0, 1, XDependencySettings.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXDependencySettings_Prefix(), ecorePackage.getEString(), "prefix", null, 0, 1, XDependencySettings.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXDependencySettings_Properties(), this.getXProperty(), null, "properties", null, 0, -1, XDependencySettings.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xPropertyEClass, XProperty.class, "XProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXProperty_Name(), ecorePackage.getEString(), "name", null, 0, 1, XProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getXProperty_Value(), this.getXPropertyValue(), null, "value", null, 0, 1, XProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xPropertyValueEClass, XPropertyValue.class, "XPropertyValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(xPropertyStringValueEClass, XPropertyStringValue.class, "XPropertyStringValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXPropertyStringValue_Value(), ecorePackage.getEString(), "value", null, 0, 1, XPropertyStringValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xPropertyNumberValueEClass, XPropertyNumberValue.class, "XPropertyNumberValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXPropertyNumberValue_Value(), ecorePackage.getEBigDecimal(), "value", null, 0, 1, XPropertyNumberValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xPropertyBooleanValueEClass, XPropertyBooleanValue.class, "XPropertyBooleanValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXPropertyBooleanValue_Value(), ecorePackage.getEBooleanObject(), "value", null, 0, 1, XPropertyBooleanValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xPropertyMutliValueEClass, XPropertyMutliValue.class, "XPropertyMutliValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getXPropertyMutliValue_Values(), this.getXPropertyValue(), null, "values", null, 0, -1, XPropertyMutliValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(xArchitectureKindEEnum, XArchitectureKind.class, "XArchitectureKind");
    addEEnumLiteral(xArchitectureKindEEnum, XArchitectureKind.INTERNAL);
    addEEnumLiteral(xArchitectureKindEEnum, XArchitectureKind.EXTERNAL);

    initEEnum(xFunctionParameterKindEEnum, XFunctionParameterKind.class, "XFunctionParameterKind");
    addEEnumLiteral(xFunctionParameterKindEEnum, XFunctionParameterKind.IN);
    addEEnumLiteral(xFunctionParameterKindEEnum, XFunctionParameterKind.OUT);
    addEEnumLiteral(xFunctionParameterKindEEnum, XFunctionParameterKind.IN_OUT);
    addEEnumLiteral(xFunctionParameterKindEEnum, XFunctionParameterKind.RETURN);

    initEEnum(xEventTypeEEnum, XEventType.class, "XEventType");
    addEEnumLiteral(xEventTypeEEnum, XEventType.ENTRY);
    addEEnumLiteral(xEventTypeEEnum, XEventType.EXIT);

    initEEnum(xDependencyTypeEEnum, XDependencyType.class, "XDependencyType");
    addEEnumLiteral(xDependencyTypeEEnum, XDependencyType.MESSAGE);
    addEEnumLiteral(xDependencyTypeEEnum, XDependencyType.REQUEST);
    addEEnumLiteral(xDependencyTypeEEnum, XDependencyType.REPLY);
    addEEnumLiteral(xDependencyTypeEEnum, XDependencyType.DOMAIN);
    addEEnumLiteral(xDependencyTypeEEnum, XDependencyType.LIFELINE_SEGMENT);
    addEEnumLiteral(xDependencyTypeEEnum, XDependencyType.MESSAGE_CONTROL);

    // Create resource
    createResource(eNS_URI);
  }

} //TmscXtextPackageImpl
