////
  // Copyright (c) 2018-2023 TNO and Contributors to the GitHub community
  //
  // This program and the accompanying materials are made available
  // under the terms of the MIT License which is available at
  // https://opensource.org/licenses/MIT
  //
  // SPDX-License-Identifier: MIT
////

ifndef::pps-version-enduser[:pps-version-enduser: dev]
ifndef::pps-binary-prefix[:pps-binary-prefix: pps]
ifndef::pps-binary-version-enduser[:pps-binary-version-enduser: pps-dev]

:idprefix:
:idseparator: -

// Enable custom style in index-docinfo.html
:docinfo:

:!table-caption:


:win-x64: win32.win32.x86_64.zip

= Platform Performance Suite (PPS)

The Platform Performance Suite (PPS) provides insight in software execution over time and enables automatic performance diagnostics.
Various generic analysis techniques like critical path, root-cause, outlier identification analysis can be applied to the Timed Message Sequence Chart (TMSC) model.
The TMSC-models, as well as the results of the analysis, are presented to the user by various visualizations focusing on facilitating the diagnosis at specific abstraction levels.

== Downloads

The Platform Performance Suite (PPS) is available as a portable IDE and also as a feature for the Eclipse IDE through the P2 update site repository.

.IDE

The PPS IDE offers the most complete and integrated experience, from convenient editing to execution of the various tools.
It suits most users.

The PPS IDE is portable, so just download, extract, and run it, to get started quickly.

.Download PPS IDE {pps-version-enduser} (link:userguide/index.html#release-notes[release notes])
[cols="2,^1"]
|===
|Windows x64 (64-bit)
|https://github.com/TNO/PPS/releases/download/{pps-version-enduser}/{pps-binary-version-enduser}-{win-x64}[download]

|===

Windows::
  * Extract the downloaded archive somewhere on your hard disk:
  ** Extract to a directory where you have read and write access.
  ** There is no need to extract to an empty folder, as all files in the archive are contained within a root folder.
  ** Don't extract in too deep a path as then you may get issues with too long paths.
  * Execute `pps.exe` from the directory that contains the extracted files to launch the PPS IDE.


.P2 update site

The PPS P2 update site contains all plugins and features, for easy integration into OSGi-based applications.

PPS {pps-version-enduser} is available as an Eclipse P2 update site:

`\https://tno.github.io/PPS/update-site/{pps-version-enduser}/`

== Learn more

For more information about PPS, please read the link:userguide/index.html[PPS user guide].

== Legal

The material in this documentation is Copyright (c) 2018-2023 TNO and Contributors to the GitHub community.

*License*

MIT License

Copyright (c) 2023 TNO

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
