/**
 * Generated by Xtext, all rights reserved ESI (TNO)
 */
package nl.esi.pps.tmsc.xtext.tmscXtext;

import java.math.BigDecimal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XDependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getTypeObject <em>Type Object</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getName <em>Name</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getTimeBound <em>Time Bound</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getScheduled <em>Scheduled</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getRequest <em>Request</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getMessage <em>Message</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXDependency()
 * @model
 * @generated
 */
public interface XDependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Object</em>' containment reference.
   * @see #setTypeObject(XDependencyTypeObject)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXDependency_TypeObject()
   * @model containment="true"
   * @generated
   */
  XDependencyTypeObject getTypeObject();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getTypeObject <em>Type Object</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Object</em>' containment reference.
   * @see #getTypeObject()
   * @generated
   */
  void setTypeObject(XDependencyTypeObject value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXDependency_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Time Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Bound</em>' attribute.
   * @see #setTimeBound(BigDecimal)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXDependency_TimeBound()
   * @model
   * @generated
   */
  BigDecimal getTimeBound();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getTimeBound <em>Time Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Bound</em>' attribute.
   * @see #getTimeBound()
   * @generated
   */
  void setTimeBound(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Scheduled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scheduled</em>' attribute.
   * @see #setScheduled(Boolean)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXDependency_Scheduled()
   * @model
   * @generated
   */
  Boolean getScheduled();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getScheduled <em>Scheduled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scheduled</em>' attribute.
   * @see #getScheduled()
   * @generated
   */
  void setScheduled(Boolean value);

  /**
   * Returns the value of the '<em><b>Request</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Request</em>' reference.
   * @see #setRequest(XDependency)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXDependency_Request()
   * @model
   * @generated
   */
  XDependency getRequest();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getRequest <em>Request</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Request</em>' reference.
   * @see #getRequest()
   * @generated
   */
  void setRequest(XDependency value);

  /**
   * Returns the value of the '<em><b>Message</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' reference.
   * @see #setMessage(XDependency)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXDependency_Message()
   * @model
   * @generated
   */
  XDependency getMessage();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XDependency#getMessage <em>Message</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' reference.
   * @see #getMessage()
   * @generated
   */
  void setMessage(XDependency value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link nl.esi.pps.tmsc.xtext.tmscXtext.XProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXDependency_Properties()
   * @model containment="true"
   * @generated
   */
  EList<XProperty> getProperties();

} // XDependency
