/**
 * Generated by Xtext, all rights reserved ESI (TNO)
 */
package nl.esi.pps.tmsc.xtext.tmscXtext;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XFunction Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameter#getKind <em>Kind</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameter#getName <em>Name</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameter#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXFunctionParameter()
 * @model
 * @generated
 */
public interface XFunctionParameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * The literals are from the enumeration {@link nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameterKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameterKind
   * @see #setKind(XFunctionParameterKind)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXFunctionParameter_Kind()
   * @model
   * @generated
   */
  XFunctionParameterKind getKind();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameter#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameterKind
   * @see #getKind()
   * @generated
   */
  void setKind(XFunctionParameterKind value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXFunctionParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XFunctionParameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link nl.esi.pps.tmsc.xtext.tmscXtext.XProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXFunctionParameter_Properties()
   * @model containment="true"
   * @generated
   */
  EList<XProperty> getProperties();

} // XFunctionParameter
