/**
 * Generated by Xtext, all rights reserved ASML / ESI (TNO)
 */
package nl.esi.pps.tmsc.xtext.tmscXtext;

import java.math.BigDecimal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XHost</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XHost#isUntraced <em>Untraced</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XHost#getTimeBound <em>Time Bound</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XHost#getScheduled <em>Scheduled</em>}</li>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XHost#getExecutors <em>Executors</em>}</li>
 * </ul>
 *
 * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXHost()
 * @model
 * @generated
 */
public interface XHost extends XNamedArchitectureElement
{
  /**
   * Returns the value of the '<em><b>Untraced</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Untraced</em>' attribute.
   * @see #setUntraced(boolean)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXHost_Untraced()
   * @model
   * @generated
   */
  boolean isUntraced();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XHost#isUntraced <em>Untraced</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Untraced</em>' attribute.
   * @see #isUntraced()
   * @generated
   */
  void setUntraced(boolean value);

  /**
   * Returns the value of the '<em><b>Time Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Bound</em>' attribute.
   * @see #setTimeBound(BigDecimal)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXHost_TimeBound()
   * @model
   * @generated
   */
  BigDecimal getTimeBound();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XHost#getTimeBound <em>Time Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Bound</em>' attribute.
   * @see #getTimeBound()
   * @generated
   */
  void setTimeBound(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Scheduled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scheduled</em>' attribute.
   * @see #setScheduled(Boolean)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXHost_Scheduled()
   * @model
   * @generated
   */
  Boolean getScheduled();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XHost#getScheduled <em>Scheduled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scheduled</em>' attribute.
   * @see #getScheduled()
   * @generated
   */
  void setScheduled(Boolean value);

  /**
   * Returns the value of the '<em><b>Executors</b></em>' containment reference list.
   * The list contents are of type {@link nl.esi.pps.tmsc.xtext.tmscXtext.XExecutor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Executors</em>' containment reference list.
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXHost_Executors()
   * @model containment="true"
   * @generated
   */
  EList<XExecutor> getExecutors();

} // XHost
