/**
 * Generated by Xtext, all rights reserved ESI (TNO)
 */
package nl.esi.pps.tmsc.xtext.tmscXtext;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XInterface</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XInterface#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXInterface()
 * @model
 * @generated
 */
public interface XInterface extends XNamedArchitectureElement
{
  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
   * The list contents are of type {@link nl.esi.pps.tmsc.xtext.tmscXtext.XOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference list.
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXInterface_Operations()
   * @model containment="true"
   * @generated
   */
  EList<XOperation> getOperations();

} // XInterface
