/**
 * Generated by Xtext, all rights reserved ESI (TNO)
 */
package nl.esi.pps.tmsc.xtext.tmscXtext;

import java.math.BigDecimal;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XTime Bound Analysis</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.esi.pps.tmsc.xtext.tmscXtext.XTimeBoundAnalysis#getDefaultTimeBound <em>Default Time Bound</em>}</li>
 * </ul>
 *
 * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXTimeBoundAnalysis()
 * @model
 * @generated
 */
public interface XTimeBoundAnalysis extends XTmscAnalysis
{
  /**
   * Returns the value of the '<em><b>Default Time Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Time Bound</em>' attribute.
   * @see #setDefaultTimeBound(BigDecimal)
   * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXTimeBoundAnalysis_DefaultTimeBound()
   * @model
   * @generated
   */
  BigDecimal getDefaultTimeBound();

  /**
   * Sets the value of the '{@link nl.esi.pps.tmsc.xtext.tmscXtext.XTimeBoundAnalysis#getDefaultTimeBound <em>Default Time Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Time Bound</em>' attribute.
   * @see #getDefaultTimeBound()
   * @generated
   */
  void setDefaultTimeBound(BigDecimal value);

} // XTimeBoundAnalysis
