/**
 * Generated by Xtext, all rights reserved ESI (TNO)
 */
package nl.esi.pps.tmsc.xtext.tmscXtext;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XTmsc Analysis</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.esi.pps.tmsc.xtext.tmscXtext.TmscXtextPackage#getXTmscAnalysis()
 * @model
 * @generated
 */
public interface XTmscAnalysis extends EObject
{
} // XTmscAnalysis
