<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metric" nsURI="http://www.esi.nl/tmsc/metric" nsPrefix="tmsc_metric">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="[[metric-ecore-diagram]]&#xD;&#xA;.Diagram of the Metric meta-model&#xD;&#xA;image::{metamodelsdir}/metric.png[]&#xD;&#xA;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MetricModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metric" containment="true" resolveProxies="false" eKeys="#//Metric/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//MetricCategory" containment="true" resolveProxies="false" eKeys="#//MetricCategory/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetricCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metric" eOpposite="#//Metric/category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="budget" eType="ecore:EDataType ../../nl.esi.pps.tmsc/model/tmsc.ecore#//EDuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" lowerBound="1"
        eType="#//MetricCategory" eOpposite="#//MetricCategory/metrics"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//MetricInstance" containment="true" resolveProxies="false" eOpposite="#//MetricInstance/metric"
        eKeys="#//MetricInstance/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tmscs" upperBound="-1"
        eType="ecore:EClass ../../nl.esi.pps.tmsc/model/tmsc.ecore#//FullScopeTMSC">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The TMSCs that were analyzed to resolve the Metric instances that are contained by this Metric."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetricInstance" eSuperTypes="../../nl.esi.pps.tmsc/model/tmsc.ecore#//Interval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="get" value="return MetricImplQueries.getNameImpl(this);"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exceedsBudget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="get" value="return MetricImplQueries.isExceedsBudgetImpl(this);"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" lowerBound="1"
        eType="#//Metric" eOpposite="#//Metric/instances"/>
  </eClassifiers>
</ecore:EPackage>
